### PR TITLE
Resolve "type is not subscriptable" error.

### PR DESCRIPTION
**Pull request by domdellumich**

### CODE REVIEW

**Comment by Lars147** [comment]
already resolved in https://github.com/saleweaver/python-amazon-sp-api/pull/717

**Comment by domdellumich** [comment]
Nope, it doesn't. Go on Google Colab and try to import the library - it has the same error. You can't subscript a list, making it capitalized doesn't fix the issue.

**Comment by domdellumich** [comment]
@saleweaver Hey Mike - mind taking a look at this change? It's quite simple, but as is the library is broken without this in place.

**Comment by Lars147** [comment]
> Nope, it doesn't. Go on Google Colab and try to import the library - it has the same error. You can't subscript a list, making it capitalized doesn't fix the issue.

This is not true. As you might see in the PR I mentioned. `List` is imported through the `typing` library.

You can read more on this here: https://docs.python.org/3.6/library/typing.html#type-aliases

Are you installing from pip or GitHub directly?

**Comment by domdellumich** [comment]
Correct, my apologies.

**Pull request closed without merging**
