### PR TITLE
Allow use of EC2 instance profile

### PR DESCRIPTION
**Pull request by jholkeboer**
This would allow the option of not providing AWS Access Keys and IDs explicitly and instead using the default boto3 Session.

I was running this from an EC2 instance that uses a role which has assume-role access to the role I use with SP API.  Because the call to the STS client doesn't include a session token, it can't use the assumed role credentials and gets this exception: `botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.`

This was my way of working around the issue.  I am open to implement it differently but I think it would be valuable to be able to work with session credentials.

### CODE REVIEW

**Comment by legenduno** [comment]
@jholkeboer @saleweaver Thanks guys, The only thing I wish is that there was documentation.

**Comment by saleweaver** [comment]
@legenduno It's pretty well documented already, what don't you understand?

**Comment by legenduno** [comment]
@saleweaver For example, this is how I get orders:
`order_list = orders.get_orders(
            CreatedAfter=(
                datetime.datetime.utcnow() - datetime.timedelta(days=14)
            ).isoformat(),
            OrderStatuses=["Unshipped"],
            MarketplaceIds="A13V1IB3VIYZZH,A1805IZSGTT6HS",  
        )
`

In documentation it says : `Args: key MarketplaceIds: [str]`, which would be `["A13V1IB3VIYZZH","A1805IZSGTT6HS"]`
If I do as documentation suggests, i only receive orders from last ID in the list.

**Comment by legenduno** [comment]
@saleweaver Please forgive me even mentioning documentation, instead of complaining I could suggest PR, sorry :)

**Pull request merged**
