### PR TITLE
md5 hash wont work against aws

### PR DESCRIPTION
**Pull request by denisneuf**
Hi @saleweaver 

return hash_md5.hexdigest() in helpers.py

will lead to an error:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidDigest</Code><Message>The Content-MD5 you specified was invalid.</Message><Content-MD5>442e96126bb485c3aad12f6cb49d8cf3</Content-MD5><RequestId>RequestId</RequestId><HostId> HostId</HostId></Error>
```

When trying to upload to the url provided in the uploadDestinationId.

```
        res = Upload().upload_document(
            resource=path,
            file=buffer,
            content_type=c_type
        )
```

I mean it will return a right payload with apparently good headers like:

`{'x-amz-server-side-encryption': 'aws:kms', 'Content-MD5': '442e96126bb485c3aad12f6cb49d8cf3'}`

but when you try to use this headers + the url provided by the Upload API will show the The Content-MD5 you specified was invalid.

So need to be replaced with:

return base64.b64encode(hash_md5.digest()).decode()

which will provide a right md5 hash when creating the uploadDestinationId and will allow you to upload the file without errors with the requests module after getting the url to upload + the headers:

`{'x-amz-server-side-encryption': 'aws:kms', 'Content-MD5': 'RC6WEmu0hcOq0S9stJ2M8w=='}`

Kindest regards,
@denisneuf

### CODE REVIEW

**Review by saleweaver — COMMENTED** [review]
We identified new issues on unchanged lines of code. Navigate to the Amazon CodeGuru Reviewer console to view the recommendations to fix them.

**Comment by denisneuf** [comment]
Do you know what is the problem of that Amazon Code Guru error? @saleweaver

**Comment by saleweaver** [comment]
That's code guru's recommendation @denisneuf: 

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more ](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512.

[Learn more ](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

Misuse of cryptography-related APIs can create security vulnerabilities. This includes algorithms with known weaknesses, certain padding modes, lack of integrity checks, insufficiently large key sizes, and insecure combinations of the aforementioned.


I'd say it's save to ignore for the use case.

**Comment by denisneuf** [comment]
Well, is Amazon who decided md5 to check the integrity of the file uploaded, what is sure is that if you don't use the Base64 it won't work ; )

**Comment by saleweaver** [comment]
> Well, is Amazon who decided md5 to check the integrity of the file uploaded, what is sure is that if you don't use the Base64 it won't work ; )

Exactly.. 😄

**Pull request merged**
