### PR TITLE
add product pricing endpoint

### PR DESCRIPTION
**Pull request by audi-thrasio**
* Adding generated code and updates to init.py for product pricing endpoint. I've run this locally against a few accounts and the code does work as I'd expect it to
* Also noticed that jinja2 is not in requirements.txt, but is required to run the codegen. I'm happy to pull this out if the omission is intentional!

### CODE REVIEW

**Comment by audi-thrasio** [comment]
I didn't see any specific guidelines on PR request / process. Please do correct me if I missed a step!

**Comment by saleweaver** [comment]
Hey @audi-thrasio !

Thanks for the PR (and the jinja reminder, thanks  😄). 

I had created a couple of custom methods for this endpoint to make it a bit more comfortable to work with. You can find the client here:

https://github.com/saleweaver/python-amazon-sp-api/blob/master/sp_api/api/products/products.py

The methods are only split by sku and asin, but it should be all that are available for product pricing. This is one of the oldest and wasn't created automatically, that's why it doesn't follow the other endpoints "conventions". 

Does the endpoint work for you? I could also add the custom methods to the ones you auto-generated...

**Comment by audi-thrasio** [comment]
I actually had not seen your custom helpers. I think they're basically identical so the generated code is moot.

I wonder if, however, putting `pricing` in the name would help? Most of this repo seems pretty faithful to what SPAPI calls endpoints (CatalogItems, ListingItems, etc) so that's why I missed it.

I think there are a few good remaining options here, do any of them seem like the right thing to you?

- Drop the PR entirely. I have all I need
- Leave my generated code as is in the PR (duplicating the ways to access this)
- Leave the generated code and also move the Pricing helpers in to the same file
- Drop the generated code from the PR and repurpose the PR just as "add jinja2 to requirements"

**Comment by saleweaver** [comment]
Let's just rename the client and export it with `ProductPricing as Product` like below, I had something similar with FeedsV2 for backwards compatibility. https://github.com/saleweaver/python-amazon-sp-api/blob/70bb1438be97bc7af8c7a802428b4324acc4943b/sp_api/api/__init__.py#L13 

I'd do it tomorrow in the morning and release, if you want to I'm happy to use the PR

**Pull request closed without merging**
