### PR TITLE
merchant- fulfillment, nested dict function, test merchant, fix test

### PR DESCRIPTION
**Pull request by rusanpas**
- Added merchant-fulfillment model and its tests.
- Added nest_dict function to facilitate the creation of nested dictionaries from flat dictionaries.
- Fixed several tests

The get_shipments test does not work, with the sandbox data, as I had mentioned.

### CODE REVIEW

**Comment by saleweaver** [comment]
Cool, thank you! I have a couple of meetings now, I'll merge tonight.

**Comment by jakerator** [comment]
@saleweaver looks like PR is fine. Any ETA for merging?

**Comment by saleweaver** [comment]
Thanks @rusanpas and sorry for the delay, I've been too busy on other projects the last few days

**Comment by rusanpas** [comment]
Thanks.

I've been using my fork while, no problem.

**Pull request merged**
