### PR TITLE
Fixed put_listings_item

### PR DESCRIPTION
**Pull request by denisneuf**
Same problem, endpoint need to 2 path params not only one:
<!DOCTYPE html>

Path | sellerId  required | A selling partner identifier, such as a merchant account or vendor code. | string
-- | -- | -- | --
Path | sku  required | A selling partner provided identifier for an Amazon listing. | string

The body param required need to be isolated from the **kwargs as data=kwargs.get('body')

<!DOCTYPE html>

Body | body  required | The request body schema for the putListingsItem operation.
-- | -- | --

The regular call could be:

# For reference only
seller_id = 'AXXXXXXXXXXXXX'
seller_sku = 'NEW-SKU-TR-7838383884'
issue_locale = 'es_ES'
marketplace_id = 'A1RKKUPIHCS9HS'

dictionary = {
    "productType": "LUGGAGE",
    "requirements": "LISTING",
    "attributes": {
        "recommended_browse_nodes": [
            {
                "value": "2008004031",
                "marketplace_id": "A1RKKUPIHCS9HS"
            }
        ],
        ...
    }
}

try:

    res = ListingsItems(account=store, marketplace=marketplace).put_listings_item(
        sellerId=seller_id,
        sku=seller_sku,
        marketplaceIds=marketplace_id_es,
        issueLocale=issue_locale,
        body=dictionary
    )

    logging.info(res)

except SellingApiException as ex:
    print(ex)

### CODE REVIEW

**Comment by saleweaver** [comment]
That doesn't look like in line with all other calls, let me check tonight - will merge or fix later.

**Comment by denisneuf** [comment]
> That doesn't look like in line with all other calls, let me check tonight - will merge or fix later.

ok thank you

**Comment by saleweaver** [comment]
Have you tested if the first commit works? Would actually make sense to keep it like you've done.

**Comment by denisneuf** [comment]
> Have you tested if the first commit works? Would actually make sense to keep it like you've done.

Yes I have tested:

 'payload': {'issues': [],
             'sku': 'NEW-SKU-TR-783838XXXXX',
             'status': 'ACCEPTED',
             'submissionId': 'ab56a7cfd7124eb8bd26842955d12345'}}

Maybe you can find a more elegant solution : )

**Comment by saleweaver** [comment]
I've merged it, I think it makes sense to have it like this for the endpoint. Thank you!

**Pull request merged**
