### PR TITLE
More flexibility when it comes to boto auth

### PR DESCRIPTION
**Pull request by nicuzs**
Considering that the application may run inside a VPC without having to auth at all in order to use aws resources, 
or that the user may have MFA or AWS SSO enabled and thus, next to key and secret, the session token argument must also be provided; 
I believe the `aws_access_key` and `aws_secret_key` should NOT be required arguments, but only passed to boto if provided, allowing boto session instance to be created without these arguments if needed.

P.S. i'm not sure how to run the tests locally, when i run `pytest` i just get a 
`=============================================================== 87 failed, 22 passed, 3 warnings in 57.71s ===============================================================`
all errors being `AuthorizationErrors` or `MissingCredentials` even though i exported them as env vars beforehand, 
similar to this open discussion https://github.com/saleweaver/python-amazon-sp-api/discussions/485

### CODE REVIEW

**Comment by nicuzs** [comment]
Hi @saleweaver , any thoughts on this topic?

**Comment by saleweaver** [comment]
Hey @nicuzs,

sorry, I was away for some days.

I was looking into this before as well, do you want the changes to make it run better on AWS, or to use other credentials in general?

**Comment by nicuzs** [comment]
> Hey @nicuzs,
> 
> sorry, I was away for some days.
> 
> I was looking into this before as well, do you want the changes to make it run better on AWS, or to use other credentials in general?

Hi, sure, no problem, thanks for getting back to me. 

I want to make these changes mainly because my app runs in a VPC, so for any other previous interactions i had with other aws resources, I didn't use authentication by allowing boto to connect without providing any. 
Also, in my dev environment,(because of MFA) I'm forced to use a set of temporary credentials, meaning next to aws `aws_access_key_id` and `aws_secret_access_key`, i MUST also provide the `aws_session_token`, otherwise the authentication is not successful, but this is currently not supported by `python-amazon-sp-api` either. 

So for both my use cases, the  current auth approach used in `python-amazon-sp-api` makes it unusable so I had to fork it and install the app directly from the git fork repo in order to bypass this limitation.


Also, conceptually speaking, boto provides by default a few authentication methods:
1. no auth
2. auth by providing `aws_access_key_id`&`aws_secret_access_key` as kwargs
3. auth by providing `aws_access_key_id`&`aws_secret_access_key` & `aws_session_token` as kwargs
4. auth by providing `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` as environment variables
5. auth by providing `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` & `AWS_SESSION_TOKEN` as environment variables
6. maybe other options which I'm not aware of, or which will be added in the future

while `python-amazon-sp-api` is sort of a wrapper on top of `boto3`( or more accurately is a library using boto3 just to connect to sts or a couple other aws resources), why would it pick just the 2.nd auth method? and make all other unsupported? 

Looking forward to your opinion, thanks !

**Comment by nicuzs** [comment]
@saleweaver Any reason for closing this ?

**Comment by nicuzs** [comment]
@saleweaver more details about closing this please? was this already merged into master from other source ?

**Pull request closed without merging**
